### ISSUE TITLE
shopkeeper.player.sell permission is ignored

### ISSUE THREAD

**Issue by timmyrs** [Shopkeepers/Shopkeepers#536]
* Shopkeepers version: `2.4.1`
* Spigot version: `git-Paper-470 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

Using the following permissions.yml setup...

    default:
      default: true
      children:
        shopkeeper.player: false
        shopkeeper.player.sell: false
        shopkeeper.player.buy: false
        shopkeeper.player.trade: true
        shopkeeper.player.book: false

...non-OP players are able to create sell and trade shops, instead of only being able to create a trade shop:

![image](https://user-images.githubusercontent.com/11009697/49447683-70f60200-f7d7-11e8-80e9-6218c6023c1b.png)

**Comment by blablubbabc** [comment]
Try to also remove the legacy permission 'shopkeeper.player.normal'. This is basically an alias for the sell-permission, and only still exists for backwards compatibility reasons.

```
# Legacy permissions:
shopkeeper.player.normal:
    description: Create and modify selling player shopkeepers
    default: true
    children:
        shopkeeper.player.sell: true
```
