### ISSUE TITLE
Item attributes disappearing between 1.21.1 and 1.21.4

### ISSUE THREAD

**Issue by viimeinen1** [Shopkeepers/Shopkeepers#962]
Item attributes disappear when updating from `1.21.1` paper to `1.21.4` paper in items saved in shops.

This happens on the newest version of the plugin currently (`Shopkeepers-2.23.5`).

The issue seems to be caused by paper item meta serialization changes in 1.21.4 or other version.

The issue can be reproduced by:

```
1. Load 1.21.1 server with ItemEdit and Shopkeepers. (or other item edit plugin).
2. Save a shop with custom attributes (attack damage 1000 etc.).
3. Update to 1.21.4

4. The attributes are no longer working
```

Here is a example of attributes I tested the issue with:  
![Image](https://github.com/user-attachments/assets/a91ec3c6-cf96-4854-b438-372f06fcf188)

Both lore, item names and enchantments converted over correctly.

Here is a shopkeeper with a save with bugged item:

```
data-version: 3|2|4189
'1':
  uniqueId: 7f05785a-33c1-4a23-8d08-65dba648a38a
  world: world
  x: 6
  y: 77
  z: 22
  yaw: 178.05328
  type: admin
  name: ''
  object:
    type: axolotl
    baby: false
    axolotlVariant: LUCY
  recipes:
    '1':
      resultItem:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: DIAMOND_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":[{"text":"Testing sword","strikethrough":false,"obfuscated":false,"bold":false,"italic":false,"underlined":false,"color":"gold"}]}'
          lore:
          - '{"text":"","extra":[{"text":"Some lore","strikethrough":false,"obfuscated":false,"bold":false,"italic":false,"underlined":false,"color":"dark_gray"}]}'
          - '{"text":"","extra":[{"text":"Sharpness XXX","strikethrough":false,"obfuscated":false,"bold":false,"italic":false,"underlined":false,"color":"gray"}]}'
          - '{"text":"","extra":[{"text":"","strikethrough":false,"obfuscated":false,"bold":false,"italic":false,"underlined":false,"color":"dark_gray"}]}'
          enchants:
            minecraft:sharpness: 2
          attribute-modifiers: {}
          ItemFlags:
          - HIDE_ENCHANTS
          - HIDE_ATTRIBUTES
          - HIDE_UNBREAKABLE
          Unbreakable: true
      item1:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: ACACIA_LEAVES
        amount: 8
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":["leaveCoins"]}'
          enchants:
            minecraft:mending: 1
          ItemFlags:
          - HIDE_ENCHANTS
    '2':
      resultItem:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: ACACIA_LEAVES
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":["leaveCoins"]}'
          enchants:
            minecraft:mending: 1
          ItemFlags:
          - HIDE_ENCHANTS
      item1:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: ACACIA_LOG
  snapshots: []
```

Here is the save that should be there:
```
data-version: 3|2|4189
'1':
  uniqueId: 7f05785a-33c1-4a23-8d08-65dba648a38a
  world: world
  x: 6
  y: 77
  z: 22
  yaw: 178.05328
  type: admin
  name: ''
  object:
    type: axolotl
    baby: false
    axolotlVariant: LUCY
  recipes:
    '1':
      resultItem:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: DIAMOND_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":[{"text":"Testing sword","strikethrough":false,"obfuscated":false,"bold":false,"italic":false,"underlined":false,"color":"gold"}]}'
          lore:
          - '{"text":"","extra":[{"text":"Some lore","strikethrough":false,"obfuscated":false,"bold":false,"italic":false,"underlined":false,"color":"dark_gray"}]}'
          - '{"text":"","extra":[{"text":"Sharpness XXX","strikethrough":false,"obfuscated":false,"bold":false,"italic":false,"underlined":false,"color":"gray"}]}'
          - '{"text":"","extra":[{"text":"","strikethrough":false,"obfuscated":false,"bold":false,"italic":false,"underlined":false,"color":"dark_gray"}]}'
          enchants:
            minecraft:sharpness: 2
          attribute-modifiers:
            minecraft:attack_damage:
            - ==: org.bukkit.attribute.AttributeModifier
              amount: 10000.0
              slot: hand
              operation: 0
              key: minecraft:6ca71f96-8e7b-4231-928d-12bdde8c87a8
            minecraft:attack_speed:
            - ==: org.bukkit.attribute.AttributeModifier
              amount: -2.4
              slot: hand
              operation: 0
              key: minecraft:6dd3e1ce-ef68-4e5e-8659-84b458eca55e
          ItemFlags:
          - HIDE_ENCHANTS
          - HIDE_ATTRIBUTES
          - HIDE_UNBREAKABLE
          Unbreakable: true
      item1:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: ACACIA_LEAVES
        amount: 8
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":["leaveCoins"]}'
          enchants:
            minecraft:mending: 1
          ItemFlags:
          - HIDE_ENCHANTS
    '2':
      resultItem:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: ACACIA_LEAVES
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"text":"","extra":["leaveCoins"]}'
          enchants:
            minecraft:mending: 1
          ItemFlags:
          - HIDE_ENCHANTS
      item1:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: ACACIA_LOG
  snapshots: []
```

Here is before and after with more simple item:
```
data-version: 3|2|3955
'1':
  uniqueId: fa47676a-3a6c-4e12-8d17-2007ee2a3dc8
  world: world
  x: 6
  y: 77
  z: 22
  yaw: 209.39743
  type: admin
  name: ''
  object:
    type: axolotl
    baby: false
    axolotlVariant: LUCY
  recipes:
    '1':
      resultItem:
        ==: org.bukkit.inventory.ItemStack
        v: 3955
        type: DIAMOND_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          attribute-modifiers:
            minecraft:generic.attack_damage:
            - ==: org.bukkit.attribute.AttributeModifier
              amount: 10000.0
              slot: hand
              operation: 0
              key: minecraft:2eafde15-cd4e-43b3-9354-e7f8e1bb4d76
      item1:
        ==: org.bukkit.inventory.ItemStack
        v: 3955
        type: ACACIA_LEAVES
  snapshots: []
```

```
data-version: 3|2|4189
'1':
  uniqueId: fa47676a-3a6c-4e12-8d17-2007ee2a3dc8
  world: world
  x: 6
  y: 77
  z: 22
  yaw: 209.39743
  type: admin
  name: ''
  object:
    type: axolotl
    baby: false
    axolotlVariant: LUCY
  recipes:
    '1':
      resultItem:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: DIAMOND_SWORD
      item1:
        ==: org.bukkit.inventory.ItemStack
        v: 4189
        type: ACACIA_LEAVES
  snapshots: []
```

`/version` command output:

`This server is running Paper version 1.21.4-229-ver/1.21.4@e2ca477 (2025-05-09T15:52:06Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-21-cfa3c61 (MC: 1.21.1)`
